# SUMI Theme Configuration
# Edit values and restart device to apply

[theme]
name = Light

[colors]
inverted_mode = false
background = white

[selection]
fill_color = black
text_color = white

[text]
primary_color = black
secondary_color = black

[layout]
margin_top = 9
margin_side = 3
item_height = 30
item_spacing = 0
item_padding_x = 8
item_value_padding = 20

[fonts]
ui_font = 
reader_font_xsmall = 
reader_font_small = 
reader_font_medium = 
reader_font_large = 
